# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4808718991f90c31b74d6e2c3e3e14cf"
name = "inverty-track"
application_url = "https://localhost"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hhuyu4-5r.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://localhost/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
